import type { Metadata } from "next";
import ClientHeaderProvider from "./layout/header/ClientHeaderProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-900">
        <ClientHeaderProvider>
          <main>{children}</main>
        </ClientHeaderProvider>
      </body>
    </html>
  );
}