import type { Metadata } from "next";
import ClientHeaderProvider from "./layout/header/ClientHeaderProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-900 flex h-[100vh] flex-col">
        <ClientHeaderProvider/>
          <main className="mt-[100px]">{children}</main>
      </body>
    </html>
  );
}